import { Player, MonthlyData, BracketMatch } from '../types';

interface AppState {
  players: Player[];
  monthlyData: MonthlyData[];
  currentMonthIndex: number;
  masterBracket: BracketMatch[];
}

// This object is now used as a one-time seed for the Firestore database.
export const INITIAL_STATE: AppState = {
  "players": [
    {
      "id": 1,
      "name": "Andre Mota",
      "totalPoints": 41,
      "wins": 2,
      "losses": 6,
      "gamesPlayed": 8,
      "setsWon": 5,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 2,
      "name": "Arildo",
      "totalPoints": 27,
      "wins": 1,
      "losses": 7,
      "gamesPlayed": 8,
      "setsWon": 3,
      "pointsFromGames": 14,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 3,
      "name": "Arthur",
      "totalPoints": 66,
      "wins": 4,
      "losses": 4,
      "gamesPlayed": 8,
      "setsWon": 10,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 4,
      "name": "Ary",
      "totalPoints": 77,
      "wins": 5,
      "losses": 3,
      "gamesPlayed": 8,
      "setsWon": 11,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 5,
      "name": "Caio Dias",
      "totalPoints": 86,
      "wins": 6,
      "losses": 2,
      "gamesPlayed": 8,
      "setsWon": 12,
      "pointsFromGames": 14,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 6,
      "name": "Claudio",
      "totalPoints": 90,
      "wins": 6,
      "losses": 2,
      "gamesPlayed": 8,
      "setsWon": 14,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 7,
      "name": "Cleiton",
      "totalPoints": 76,
      "wins": 5,
      "losses": 3,
      "gamesPlayed": 8,
      "setsWon": 10,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 8,
      "name": "Daniel Tomaz",
      "totalPoints": 88,
      "wins": 6,
      "losses": 2,
      "gamesPlayed": 8,
      "setsWon": 12,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 9,
      "name": "Diego Rodrigues",
      "totalPoints": 77,
      "wins": 5,
      "losses": 3,
      "gamesPlayed": 8,
      "setsWon": 11,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 10,
      "name": "Evaldo",
      "totalPoints": 79,
      "wins": 5,
      "losses": 3,
      "gamesPlayed": 8,
      "setsWon": 13,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 11,
      "name": "Fernando Garpelli",
      "totalPoints": 52,
      "wins": 3,
      "losses": 5,
      "gamesPlayed": 8,
      "setsWon": 6,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 12,
      "name": "Fernando Martin",
      "totalPoints": 51,
      "wins": 3,
      "losses": 5,
      "gamesPlayed": 8,
      "setsWon": 7,
      "pointsFromGames": 14,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 13,
      "name": "Fernando Soares",
      "totalPoints": 65,
      "wins": 4,
      "losses": 4,
      "gamesPlayed": 8,
      "setsWon": 9,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 14,
      "name": "Flavio",
      "totalPoints": 54,
      "wins": 3,
      "losses": 5,
      "gamesPlayed": 8,
      "setsWon": 8,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 15,
      "name": "Gabriel Abrame",
      "totalPoints": 66,
      "wins": 4,
      "losses": 4,
      "gamesPlayed": 8,
      "setsWon": 10,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 16,
      "name": "Gilson Santana",
      "totalPoints": 50,
      "wins": 3,
      "losses": 5,
      "gamesPlayed": 8,
      "setsWon": 6,
      "pointsFromGames": 14,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 17,
      "name": "Guilherme Tadini",
      "totalPoints": 88,
      "wins": 6,
      "losses": 2,
      "gamesPlayed": 8,
      "setsWon": 12,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 18,
      "name": "Gustavo Granja",
      "totalPoints": 76,
      "wins": 5,
      "losses": 3,
      "gamesPlayed": 8,
      "setsWon": 10,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 19,
      "name": "Iramaia",
      "totalPoints": 67,
      "wins": 4,
      "losses": 4,
      "gamesPlayed": 8,
      "setsWon": 11,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 20,
      "name": "Joao Claudio",
      "totalPoints": 65,
      "wins": 4,
      "losses": 4,
      "gamesPlayed": 8,
      "setsWon": 9,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 21,
      "name": "Joao Vicente",
      "totalPoints": 43,
      "wins": 2,
      "losses": 6,
      "gamesPlayed": 8,
      "setsWon": 7,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 22,
      "name": "João Orsi",
      "totalPoints": 56,
      "wins": 3,
      "losses": 5,
      "gamesPlayed": 8,
      "setsWon": 10,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 23,
      "name": "José Eduardo",
      "totalPoints": 78,
      "wins": 5,
      "losses": 3,
      "gamesPlayed": 8,
      "setsWon": 12,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 24,
      "name": "Leo Alves",
      "totalPoints": 88,
      "wins": 6,
      "losses": 2,
      "gamesPlayed": 8,
      "setsWon": 12,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 25,
      "name": "Lincoln",
      "totalPoints": 100,
      "wins": 7,
      "losses": 1,
      "gamesPlayed": 8,
      "setsWon": 14,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 26,
      "name": "Luan",
      "totalPoints": 40,
      "wins": 2,
      "losses": 6,
      "gamesPlayed": 8,
      "setsWon": 4,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 27,
      "name": "Lucas Lima",
      "totalPoints": 62,
      "wins": 4,
      "losses": 4,
      "gamesPlayed": 8,
      "setsWon": 8,
      "pointsFromGames": 14,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 28,
      "name": "Luiz Fernando",
      "totalPoints": 35,
      "wins": 2,
      "losses": 6,
      "gamesPlayed": 8,
      "setsWon": 5,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 29,
      "name": "Marcelo Bassi",
      "totalPoints": 27,
      "wins": 1,
      "losses": 7,
      "gamesPlayed": 8,
      "setsWon": 4,
      "pointsFromGames": 4,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 30,
      "name": "Marcelo Candido",
      "totalPoints": 77,
      "wins": 5,
      "losses": 3,
      "gamesPlayed": 8,
      "setsWon": 11,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 31,
      "name": "Marcos Rodrigues",
      "totalPoints": 64,
      "wins": 4,
      "losses": 4,
      "gamesPlayed": 8,
      "setsWon": 8,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 32,
      "name": "Mario",
      "totalPoints": 65,
      "wins": 4,
      "losses": 4,
      "gamesPlayed": 8,
      "setsWon": 9,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 33,
      "name": "Paulo Soares",
      "totalPoints": 47,
      "wins": 3,
      "losses": 5,
      "gamesPlayed": 8,
      "setsWon": 7,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 34,
      "name": "Pedro",
      "totalPoints": 58,
      "wins": 4,
      "losses": 4,
      "gamesPlayed": 8,
      "setsWon": 8,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 35,
      "name": "Rafael Brandao",
      "totalPoints": 41,
      "wins": 2,
      "losses": 6,
      "gamesPlayed": 8,
      "setsWon": 5,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 36,
      "name": "Renan Martin",
      "totalPoints": 66,
      "wins": 4,
      "losses": 4,
      "gamesPlayed": 8,
      "setsWon": 10,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 37,
      "name": "Robson Fiusa",
      "totalPoints": 101,
      "wins": 7,
      "losses": 1,
      "gamesPlayed": 8,
      "setsWon": 15,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 38,
      "name": "Tadeu Maia",
      "totalPoints": 4,
      "wins": 0,
      "losses": 8,
      "gamesPlayed": 8,
      "setsWon": 0,
      "pointsFromGames": 4,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 39,
      "name": "Thiago Mello",
      "totalPoints": 90,
      "wins": 6,
      "losses": 2,
      "gamesPlayed": 8,
      "setsWon": 14,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 40,
      "name": "Tiago Meira",
      "totalPoints": 66,
      "wins": 4,
      "losses": 4,
      "gamesPlayed": 8,
      "setsWon": 10,
      "pointsFromGames": 16,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    }
  ],
  "monthlyData": [
    {
      "id": 1,
      "name": "Dezembro",
      "groups": [
        { "id": 1, "name": "Grupo 1", "playerIds": [37, 25, 6, 39] },
        { "id": 2, "name": "Grupo 2", "playerIds": [17, 8, 24, 5] },
        { "id": 3, "name": "Grupo 3", "playerIds": [10, 23, 4, 9] },
        { "id": 4, "name": "Grupo 4", "playerIds": [30, 18, 7, 19] },
        { "id": 5, "name": "Grupo 5", "playerIds": [15, 40, 36, 3] },
        { "id": 6, "name": "Grupo 6", "playerIds": [32, 13, 20, 31] },
        { "id": 7, "name": "Grupo 7", "playerIds": [27, 34, 22, 14] },
        { "id": 8, "name": "Grupo 8", "playerIds": [11, 12, 16, 33] },
        { "id": 9, "name": "Grupo 9", "playerIds": [21, 35, 1, 26] },
        { "id": 10, "name": "Grupo 10", "playerIds": [28, 29, 2, 38] }
      ],
      "matches": [
        { "id": "m1-g1-p37-vs-p25", "player1Id": 37, "player2Id": 25, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g1-p37-vs-p6", "player1Id": 37, "player2Id": 6, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g1-p37-vs-p39", "player1Id": 37, "player2Id": 39, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g1-p25-vs-p6", "player1Id": 25, "player2Id": 6, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g1-p25-vs-p39", "player1Id": 25, "player2Id": 39, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g1-p6-vs-p39", "player1Id": 6, "player2Id": 39, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g2-p17-vs-p8", "player1Id": 17, "player2Id": 8, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g2-p17-vs-p24", "player1Id": 17, "player2Id": 24, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g2-p17-vs-p5", "player1Id": 17, "player2Id": 5, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g2-p8-vs-p24", "player1Id": 8, "player2Id": 24, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g2-p8-vs-p5", "player1Id": 8, "player2Id": 5, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g2-p24-vs-p5", "player1Id": 24, "player2Id": 5, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g3-p10-vs-p23", "player1Id": 10, "player2Id": 23, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g3-p10-vs-p4", "player1Id": 10, "player2Id": 4, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g3-p10-vs-p9", "player1Id": 10, "player2Id": 9, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g3-p23-vs-p4", "player1Id": 23, "player2Id": 4, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g3-p23-vs-p9", "player1Id": 23, "player2Id": 9, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g3-p4-vs-p9", "player1Id": 4, "player2Id": 9, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g4-p30-vs-p18", "player1Id": 30, "player2Id": 18, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g4-p30-vs-p7", "player1Id": 30, "player2Id": 7, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g4-p30-vs-p19", "player1Id": 30, "player2Id": 19, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g4-p18-vs-p7", "player1Id": 18, "player2Id": 7, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g4-p18-vs-p19", "player1Id": 18, "player2Id": 19, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g4-p7-vs-p19", "player1Id": 7, "player2Id": 19, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g5-p15-vs-p40", "player1Id": 15, "player2Id": 40, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g5-p15-vs-p36", "player1Id": 15, "player2Id": 36, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g5-p15-vs-p3", "player1Id": 15, "player2Id": 3, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g5-p40-vs-p36", "player1Id": 40, "player2Id": 36, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g5-p40-vs-p3", "player1Id": 40, "player2Id": 3, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g5-p36-vs-p3", "player1Id": 36, "player2Id": 3, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g6-p32-vs-p13", "player1Id": 32, "player2Id": 13, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g6-p32-vs-p20", "player1Id": 32, "player2Id": 20, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g6-p32-vs-p31", "player1Id": 32, "player2Id": 31, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g6-p13-vs-p20", "player1Id": 13, "player2Id": 20, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g6-p13-vs-p31", "player1Id": 13, "player2Id": 31, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g6-p20-vs-p31", "player1Id": 20, "player2Id": 31, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g7-p27-vs-p34", "player1Id": 27, "player2Id": 34, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g7-p27-vs-p22", "player1Id": 27, "player2Id": 22, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g7-p27-vs-p14", "player1Id": 27, "player2Id": 14, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g7-p34-vs-p22", "player1Id": 34, "player2Id": 22, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g7-p34-vs-p14", "player1Id": 34, "player2Id": 14, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g7-p22-vs-p14", "player1Id": 22, "player2Id": 14, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g8-p11-vs-p12", "player1Id": 11, "player2Id": 12, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g8-p11-vs-p16", "player1Id": 11, "player2Id": 16, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g8-p11-vs-p33", "player1Id": 11, "player2Id": 33, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g8-p12-vs-p16", "player1Id": 12, "player2Id": 16, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g8-p12-vs-p33", "player1Id": 12, "player2Id": 33, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g8-p16-vs-p33", "player1Id": 16, "player2Id": 33, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g9-p21-vs-p35", "player1Id": 21, "player2Id": 35, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g9-p21-vs-p1", "player1Id": 21, "player2Id": 1, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g9-p21-vs-p26", "player1Id": 21, "player2Id": 26, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g9-p35-vs-p1", "player1Id": 35, "player2Id": 1, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g9-p35-vs-p26", "player1Id": 35, "player2Id": 26, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g9-p1-vs-p26", "player1Id": 1, "player2Id": 26, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g10-p28-vs-p29", "player1Id": 28, "player2Id": 29, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g10-p28-vs-p2", "player1Id": 28, "player2Id": 2, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g10-p28-vs-p38", "player1Id": 28, "player2Id": 38, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g10-p29-vs-p2", "player1Id": 29, "player2Id": 2, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g10-p29-vs-p38", "player1Id": 29, "player2Id": 38, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g10-p2-vs-p38", "player1Id": 2, "player2Id": 38, "winnerId": null, "score": "", "isWO": false }
      ]
    }
  ],
  "currentMonthIndex": 0,
  "masterBracket": []
};
